
version: '3.6'
services:
  webapp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"

  webapp2:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"